apiVersion: v1
kind: Namespace
metadata:
  name: edgar-namespace-c2
---

#POSGRESQL

#Volumen persistente 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-edgar-vol1
  namespace: edgar-namespace-c2
spec: #Configuración de lo que va a contruir a nivel de disco
  storageClassName: almacen
  capacity:
    storage: 10Gi # Capacidad
  accessModes:
    - ReadWriteOnce # Lectura y escritura
  hostPath:
    path: "/mnt/almacen" # Lugar donde guardara los datos
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-edgar
  namespace: edgar-namespace-c2
  volumename: pv-postgres-edgar-vol1
spec:
  storageClassName: almacen
  accessModes:
    - ReadWriteOnce
  resources: #Configuración de lo que va a reclamar
    requests:
      storage: 5Gi
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: almacen
  namespace: edgar-namespace-c2
provisioner: kubernetes.io/no-provisioner #no-provisioner -> Entorno de de infraestructura local
reclaimPolicy: Retain #Que realizara con mis datos 
volumeBindingMode: WaitForFirstConsumer
---

# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-edgar
data:
  postgres_password: "1995edgar"
  postgres_user: "postgres"
  postgres_db: "corte2"
  ---

#DEPLOY postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-edgar-deployment
  namespace: edgar-namespace-c2
  labels:
    app: postgres-server-edgar
spec:
  selector:
    matchLabels:
      app: postgres-server-edgar
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-server-edgar
    spec:
      containers:
      - image: postgres:11  #docker pull image
        name: postgres-db1-edgar
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql-edgar/data
          name: postgres-edgar-volume1
        env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-edgar
                  key: postgres_password
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-edgar
                  key: postgres_user
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-edgar
                  key: postgres_db
      volumes:
      - name: postgres-edgar-volume1
      configMap:
        name: postgres-edgar
      persistentVolumeClaim:
        claimName: pvc-postgres-edgar
---

apiVersion: v1
kind: Service
metadata:
  name: service-postgres-edgar
  namespace: edgar-namespace-c2
spec:
  selector:
    app: postgres-server-edgar
  ports:
    - port: 5300
      targetPort: 5432
  type: LoadBalancer
---


#REDIS
# Volumen persistente 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-edgar-vol1
  namespace: edgar-namespace-c2
spec: #Configuración de lo que va a contruir a nivel de disco
  storageClassName: almacen
  capacity:
    storage: 10Gi # Capacidad
  accessModes:
    - ReadWriteOnce # Lectura y escritura
  hostPath:
    path: "/mnt/almacen" # Lugar donde guardara los datos
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-edgar
  namespace: edgar-namespace-c2
  volumename: pv-redis-edgar-vol1
spec:
  storageClassName: almacen
  accessModes:
    - ReadWriteOnce
  resources: #Configuración de lo que va a reclamar
    requests:
      storage: 5Gi
---


#DEPLOY redis
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-edgar-deployment
    namespace: edgar-namespace-c2
    labels:
      app: redis-server
spec:
  replicas: 1 
  selector:
    matchLabels: 
      app: redis-server
  template: 
    metadata:
      labels: 
        app: redis-server
    spec:
      containers:
        - name: redis
          image: redis
          ports:        
            - containerPort: 6379
---

apiVersion: v1
kind: Service
metadata:
  name: service-redis-edgar
spec:
  type: LoadBalancer
  selector:
    app: redis-server
  ports:
  - port: 5301
    targetPort: 6379
    protocol: TCP

#MONGO
---
#Volumen persistente 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-edgar-vol1
  namespace: edgar-namespace-c2
spec: #Configuración de lo que va a contruir a nivel de disco
  storageClassName: almacen
  capacity:
    storage: 10Gi # Capacidad
  accessModes:
    - ReadWriteOnce # Lectura y escritura
  hostPath:
    path: "/mnt/almacen" # Lugar donde guardara los datos
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo-edgar
  namespace: edgar-namespace-c2
  volumename: pv-mongo-edgar-vol1
spec:
  storageClassName: almacen
  accessModes:
    - ReadWriteOnce
  resources: #Configuración de lo que va a reclamar
    requests:
      storage: 5Gi
---



#DEPLOY mongo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-edgar-deployment
  namespace: edgar-namespace-c2
  labels:
    app: mongo-server
spec:
  selector:
    matchLabels:
      app: mongo-server-gabriel
  replicas: 1
  template:
    metadata:
      labels:
        app:  mongo-server-gabriel 
    spec:
      containers:
      - name: mongo
        image: mongo:4
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db  
          name: pv-mongo-edgar-vol1
      volumes:
      - name: pv-mongo-edgar-vol1
        persistentVolumeClaim:
          claimName: pvc-mongo-edgar 
---

apiVersion: v1
kind: Service
metadata:
  name: service-mongo-edgar
spec:
  selector:
    app: mongo-server-edgar
  ports:
    - port: 5302
      targetPort: 27017
  type: LoadBalancer
---


#MYSQL

# Volumen persistente 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-edgar-vol1
  namespace: edgar-namespace-c2
spec: #Configuración de lo que va a contruir a nivel de disco
  storageClassName: almacen
  capacity:
    storage: 10Gi # Capacidad
  accessModes:
    - ReadWriteOnce # Lectura y escritura
  hostPath:
    path: "/mnt/almacen" # Lugar donde guardara los datos
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-edgar
  namespace: edgar-namespace-c2
  volumename: pv-mysql-edgar-vol1
spec:
  storageClassName: almacen
  accessModes:
    - ReadWriteOnce
  resources: #Configuración de lo que va a reclamar
    requests:
      storage: 5Gi
---


# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql_password: "1995edgar."
---

#DEPLOY mysql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-edgar-deployment
  namespace: edgar-namespace-c2
  labels:
    app: mysql-server-edgar
spec:
  selector:
    matchLabels:
      app: mysql-server-edgar
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-server-edgar
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-edgar
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: mysql_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: pv-mysql-edgar-vol1
          mountPath: /var/lib/mysql
      volumes:
      - name: pv-mysql-edgar-vol1
      configMap: 
        name: mysql
        persistentVolumeClaim:
          claimName: pvc-mysql-edgar
---

apiVersion: v1
kind: Service
metadata:
  name: service-mysql-edgar
  namespace: edgar-namespace-c2
spec:
  selector:
    app: mysql-server-edgar
  ports:
    - port: 5303
      targetPort: 3306
  type: LoadBalancer
---